name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v5

    - uses: nuget/setup-nuget@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Update version
      run: |
        (Get-Content -Path src\ExceptionAnalyzer.Vsix\source.extension.vsixmanifest) |
          ForEach-Object {$_ -Replace '1.0.0', '1.1.${{ github.run_number }}'} |
            Set-Content -Path src\ExceptionAnalyzer.Vsix\source.extension.vsixmanifest
        (Get-Content -Path src\ExceptionAnalyzer\ExceptionAnalyzer.csproj) |
          ForEach-Object {$_ -Replace '1.0.0.0', '1.1.${{ github.run_number }}.0'} |
            Set-Content -Path src\ExceptionAnalyzer\ExceptionAnalyzer.csproj

    - name: Restore
      run: nuget restore

    - name: Build
      run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

    - uses: actions/upload-artifact@v4
      with:
        name: TheExceptionator.Analyzers.1.1.${{ github.run_number }}.nupkg
        path: src\ExceptionAnalyzer\bin\Release\TheExceptionator.Analyzers.1.1.${{ github.run_number }}.nupkg

    - uses: actions/upload-artifact@v4
      with:
        name: TheExceptionator.vsix
        path: src\ExceptionAnalyzer.Vsix\bin\Release\net472\ExceptionAnalyzer.Vsix.vsix

    - name: Create Release
      id: create_release
      if: ${{ github.event_name == 'push' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./src/ExceptionAnalyzer.Vsix/bin/Release/net472/ExceptionAnalyzer.Vsix.vsix
          ./src/ExceptionAnalyzer/bin/Release/TheExceptionator.Analyzers.1.1.${{ github.run_number }}.nupkg
        tag_name: 1.1.${{ github.run_number }}
        name: Release 1.1.${{ github.run_number }}
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push TheExceptionator.Analyzers to nuget.org
      run: dotnet nuget push src\ExceptionAnalyzer\bin\Release\TheExceptionator.Analyzers.1.1.${{ github.run_number }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}